M48
; DRILL file {KiCad 8.0.1-rc1} date 2024-09-02T14:56:06-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-09-02T14:56:06-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1-rc1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
%
G90
G05
T1
X45.995Y-91.0
X45.995Y-94.0
T2
X55.545Y-92.5
X63.045Y-92.5
M30
