M48
; DRILL file {KiCad 8.0.2} date 2024-06-27T19:58:17-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-06-27T19:58:17-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0512
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0630
%
G90
G05
T1
X6.7224Y-1.6732
X7.0079Y-1.5256
T2
X6.565Y-1.6732
X6.8504Y-1.5256
T3
X6.6535Y-1.9783
X7.126Y-1.5059
M30
